### PR TITLE
compatible syncing icon 

### PR DESCRIPTION
**Pull request by nerdlabs001**
Netcoin animation

### CODE REVIEW

**Comment by nerdlabs001** [comment]
i made clean a few times to make sure it was working correctly looks good in Linux

**Comment by Daysover** [comment]
Hi
Is it also possible to disable Unlock Wallet until blockchain is fully synced?
Thanks!

**Comment by regtable** [comment]
@Daysover it can be done yes but as to why you would need it i dont know. just dont unlock the wallet untill you see the tick appear. if its to address the early stake bug that causes you to short yourself off chain its been addressed somewhat already in 3.0. no peers no stake. and known height checks pre staking so if your not passed a certain block your wallet will try to stake and error the attempt. mush like the external peers would reject it for low height. 
but by all means we can make it so the wallet does not even load your balances untill its in full sync i.e eternal splash screen while chasing best chain height.
does this need an issue assigning to it or just more a friendly suggestion of feature?

**Comment by regtable** [comment]
@nerdlabs001 thanks for submitting this pull tested on windows build environment and still a blank image. i have managed a work around using gif support in qt to display a gif there in leiu of an mng, not 100% sure the difference except file size. however i will re build my win build environment up untill i either get the mng working in windows, or decide gif is the better way. not tested on mac yet.

**Comment by Daysover** [comment]
Hi regtable"just more a friendly suggestion of feature" yes for people just starting out..my windows64  2.5.2  takes a few minutes before the download bar starts working (at bottom of window)enough time to start thinking to unlock (for a beginner).
moug

    On Thursday, February 21, 2019, 8:44:52 a.m. MST, regtable <notifications@github.com> wrote:  
 
 
@Daysover it can be done yes but as to why you would need it i dont know. just dont unlock the wallet untill you see the tick appear. if its to address the early stake bug that causes you to short yourself off chain its been addressed somewhat already in 3.0. no peers no stake. and known height checks pre staking so if your not passed a certain block your wallet will try to stake and error the attempt. mush like the external peers would reject it for low height.
but by all means we can make it so the wallet does not even load your balances untill its in full sync i.e eternal splash screen while chasing best chain height.
does this need an issue assigning to it or just more a friendly suggestion of feature?

**Comment by regtable** [comment]
No worries. Can be looked at implementing it. All in all its safety
reasons. Shouldn't ever send unless in full sync I guess.

**Comment by Daysover** [comment]
YesI just don't want have user locked out of access of console if he/she needs to get the keys/etc for backup.So console should not be hidden or disabled if many days/weeks block-chain needs to download.
Maybe just a reminder on screen would work, where it says Please Unlock for Staking
Thanks!

    On Saturday, February 23, 2019, 3:23:24 p.m. MST, regtable <notifications@github.com> wrote:  
 
 No worries. Can be looked at implementing it. All in all its safety
reasons. Shouldn't ever send unless in full sync I guess.

**Pull request merged**
